version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - .:/app/
        links:
            - php
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: php:fpm-alpine
        volumes:
            - .:/app/

networks:
  internal:
    driver: bridge